version: '3'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ./
    container_name: app
    depends_on:
      - db

  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres