version: '3'

services:
  app:
    image: 'app:latest'
    build:
      context: ./
    container_name: app
    depends_on:
      - db

  db:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    container_name: db
    environment:
      - POSTGRES_USER=wil
      - POSTGRES_PASSWORD=wil
      - POSTGRES_DB=medhead
    networks:
      - postgres-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  postgres-network:
    driver: bridge