name: Launch containers and test them

on:
  push:
    branches:
      - master

jobs:
  Build-and-test:
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'
          
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and test with Maven
   
        run: |
          docker run -d -p 5432:5432 -e POSTGRES_USER=wil -e POSTGRES_PASSWORD=wil -e POSTGRES_DB=medhead postgres:latest
          mvn clean test -Dspring.profiles.active=test -Dspring.datasource.url=jdbc:postgresql://localhost:5432/medhead -Dspring.datasource.username=wil -Dspring.datasource.password=wil
