name: Launch containers and test them

on:
  push:
    branches:
      - master

jobs:
  launch-postgtresql:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: wil
          POSTGRES_PASSWORD: wil
          POSTGRES_DB: medhead
          ports:
            - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-image .

      - name: Start Docker container
        run: docker run -d -p 8080:8080 --name my-container --link postgres my-image

      - name: Wait for container to start
        run: docker logs -f my-container | grep "Started Application in"

    test:
      steps:
        - name: Check out code
          uses: actions/checkout@v3

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Run tests
          run: mvn clean test

    build:
      runs-on: ubuntu-latest
      steps:
        - name: Check out code
          uses: actions/checkout@v3

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Run build
          run: mvn clean install

