name: Launch containers and test them

on:
  push:
    branches:
      - restart

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run docker-compose
        run: |
          docker-compose run --rm app mvn test
          docker-compose up -f "src/main/docker/docker-compose.yml" up -d --build

