name: Launch containers and test them

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Set up Maven
        uses: apache/maven-setup-action@v2
        with:
          maven-version: '3.8.7'

      - name: Launch tests
        Run: mvn clean test jacoco:report

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code 
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Set up Maven
        uses: apache/maven-setup-action@v2
        with:
          maven-version: '3.8.7'

      - name: Launch app
        run: mvn clean install


