name: Launch containers and test them

on:
  push:
    branches:
      - master

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: wil
          POSTGRES_PASSWORD: wil
          POSTGRES_DATABASE: medhead
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Run docker-compose
        run: docker-compose up -f "src/main/docker/docker-compose.yml" up -d --build

      - name: Run tests
        run: docker-compose up -f "src/main/docker/docker-compose.yml" run test
