name: Launch containers and test them

on:
  push:
    branches:
      - restart

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Tests
        run: docker-compose run -f "src/main/docker/docker-compose.yml" --rm app mvn test

      - name: Build
        run: docker-compose up -f "src/main/docker/docker-compose.yml" up -d --build

