name: Launch containers and test them

on:
  push:
    branches:
      - restart

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Tests
        run: mvn clean test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: mvn build

