name: Launch containers and test them

on:
  push:
    branches:
      - master

jobs:
  launch-postgtresql:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: wil
          POSTGRES_PASSWORD: wil
          POSTGRES_DB: medhead

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -f '\src\main\docker\dockerfile\' -t my-image .

      - name: Start Docker container
        run: docker run -d -p 8080:8080 --name my-container --link postgres my-image

      - name: Wait for container to start
        run: docker logs -f my-container | grep "Started Application in"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        run: mvn clean test

      - name: Run build
        run: mvn clean install

