name: Launch containers and test them

on:
  push:
    branches:
      - master

jobs:
  database:
    runs-on: ubuntu-latest
    steps:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: wil
          POSTGRES_PASSWORD: wil
          POSTGRES_DB: medhead

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Launch tests
        run: mvn clean test jacoco:report


