name: Launch containers and test them

on:
  push:
    branches:
      - master

jobs:
  database:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Launch container database
        run: docker-compose up -f "src/main/docker/docker-compose.yml" up -d --build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Launch tests
        uses: database
        run: mvn clean test jacoco:report


